[project]
name = "spam-message-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "awaisalidev13", email = "awaisali.dev.13@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "streamlit>=1.63.0",
]

[project.scripts]
spam-message-detector = "spam_message_detector:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
